### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replaceAll')

### ISSUE THREAD

**Issue by teddimitrov** [Pluralith/pluralith-cli#104]
Windows 11, binary has been renamed and moved to Windows\System32 per the docs.

When I try to execute in a folder with terraform files it results in this:

pluralith.exe graph

```
Render graph and export PDF

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at C:\snapshot\pluralith-cli-graphing\dist\build\commands\Graph.js
    at Generator.next (<anonymous>)
    at C:\snapshot\pluralith-cli-graphing\dist\build\commands\Graph.js
    at new Promise (<anonymous>)
    at C:\snapshot\pluralith-cli-graphing\dist\build\commands\Graph.js
    at Graph (C:\snapshot\pluralith-cli-graphing\dist\build\commands\Graph.js)
    at C:\snapshot\pluralith-cli-graphing\dist\build\index.js
    at Generator.next (<anonymous>)
    at C:\snapshot\pluralith-cli-graphing\dist\build\index.js
    at new Promise (<anonymous>)
```

**Comment by ChipRab** [comment]
I have the exact same issue.

**Comment by marcopalumbo** [comment]
Same here

**Comment by DanThePutzer** [comment]
Thanks for reporting everyone! I've got a rough idea of what it could be. Will report back with a fix soon 👌

**Comment by DanThePutzer** [comment]
@teddimitrov @ChipRab @marcopalumbo we just released a new version of the graphing module that should fix this issue. If you simply run `pluralith` again, the latest version of the module should be installed and you should get a diagram 👍 

Let me know how it goes!

**Comment by marcopalumbo** [comment]
@DanThePutzer the new version fixed the issue... 
BTW now I'm getting a 'self signed certificate in certificate chain' error and I guess is due to SSL inspection by company firewall

I'll open a new issue on that

**Comment by DanThePutzer** [comment]
@marcopalumbo I'll close this one and jump over to the new issue!
