### ISSUE TITLE
Feature request: specify config file

### ISSUE THREAD

**Issue by sterliakov** [Pluralith/pluralith-cli#107]
I found myself doing `cp pluralith_full.yml pluralith.yml`, `cp pluralith_no_iam.yml pluralith.yml` and `cp pluralith_global.yml pluralith.yml` to create several diagrams with different detalisation (I need them locally in pdf, so that fancy "expanding" part in the webview is unrelated). Would be great to allow passing `--config` to `pluralith` executable to avoid replacing config file in place, and this should be very easy to support.

**Comment by DanThePutzer** [comment]
Hi @sterliakov 

Thanks for requesting! This was indeed quite straight-forward to implement and we just shipped a new version (`v0.2.2`) that lets you specify a custom path to a config file via the `--config-file` flag (we also added this to the docs [here](https://docs.pluralith.com/docs/commands/graph#available-flags)).

Would be awesome if you could give it a run and let me know if everything works as expected on your end!

**Comment by sterliakov** [comment]
Hi @DanThePutzer 

This works quite well, thanks a lot!
