### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by teddimitrov** [Pluralith/pluralith-cli#110]
Downloaded pluralith 0.2.2 

On Windows 11 (after moved to windows\system32 and renamed) I get:

❯ pluralith
✔ No graph module installed, found latest release
⠿ None → 0.2.1

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xe7c950]

goroutine 1 [running]:
pluralith/pkg/install.DownloadGitHubRelease({0x174aded, 0xc}, {0xc0000a6000, 0x83}, {0xc000040140, 0x41})
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/pkg/install/DownloadGitHubRelease.go:28 +0x530
pluralith/pkg/install/components.GraphModule(0x80?)
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/pkg/install/components/GraphModule.go:42 +0x2ac
main.initApp()
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/main.go:32 +0x31e
main.main()
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/main.go:42 +0x17

**Comment by teddimitrov** [comment]
The issue in this case is that I missed after downloading the new binary, to issue the pluralith update command to update the graph module.

In addition, if you have MFA configured for log in Azure "az login" will be insufficient, you need to:

az login --tenant "your tenant id here" and

Please explicitly log in with:
az login --scope https://graph.microsoft.com//.default

We can mark this as resolved.

**Comment by DanThePutzer** [comment]
Thanks for getting back to us with the fixes! This should be super helpful for people that run into similar problems when using Pluralith with Azure! 🥇
