### ISSUE TITLE
Graph Failed - Error Preprocessing Variables

### ISSUE THREAD

**Issue by CloudMarshall** [Pluralith/pluralith-cli#45]
`{
  "log": {
    "processId": 8573845,
    "errors": [
      {
        "timestamp": 1657823145629,
        "method": "",
        "log": "Error getting resource variables"
      },
      {
        "timestamp": 1657823145629,
        "method": "",
        "log": "Error: Preprocessing variables."
      },
      {
        "log": "Error: processor failed.",
        "method": ""
      }
    ],
    "dependencies": [],
    "graphingData": [],
    "placingData": [],
    "preprocessingResources": [],
    "resources": [],
    "summary": [],
    "warnings": [],
    "error": true
  }
}`

**Comment by PhiWeber** [comment]
@CloudMarshall thank you for reporting the bug! Apparently an error occurred while processing the state file. We would need more details to debug this, please email me here: phi@pluralith.com

Thanks!

**Comment by DanThePutzer** [comment]
@CloudMarshall just checking in again to see if you still face this issue and would want to share details with @PhiWeber so we can fix it up for you :)
