### ISSUE TITLE
Does the CLI currently not support M1 Mac OS?

### ISSUE THREAD

**Issue by heumsi** [Pluralith/pluralith-cli#53]
I downloaded cli binary file from following web dashboard.

<img width="1912" alt="image" src="https://user-images.githubusercontent.com/31306282/188268370-a0132bcb-7384-4706-8a62-2b57148e8acc.png">

But when I try to execute the file, following error occured.

```bash
$ sh pluralith_cli_darwin_amd64_v0.1.12

pluralith_cli_darwin_amd64_v0.1.12: pluralith_cli_darwin_amd64_v0.1.12: cannot execute binary file
```

I also found initial script for installation from official docs.

```
https://raw.githubusercontent.com/Pluralith/pluralith-cli/dev/scripts/install.sh
```

but this shell script is only for linux (ubuntu maybe).

Does the CLI currently not support M1 Mac OS?

**Comment by heumsi** [comment]
I solved this problems with installing cli by desktop app.

**Comment by DanThePutzer** [comment]
Hi @heumsi,

Apologies for the late reply! Glad to see you were able to get past it. It looks like the issue you faced first might've been a permission issue? I know that on my machine if I download the binary I have to `chmod +x` it first to make it executable. Did you try that?

Cheers,
Dan

**Comment by heumsi** [comment]
No, I did not try it. I think your method will be the solution.
