### ISSUE TITLE
pluralith run does not work with 400 bad request

### ISSUE THREAD

**Issue by heumsi** [Pluralith/pluralith-cli#54]
Hi.

Firstly, I used pluralith in github actions. but it did not worked.
I wrote the issue in [this](https://github.com/Pluralith/actions/issues/10)

Next, I downloaded desktop app and cli in my local.
but still pluralith run (manually) does not work.

This is what i did and result.

```bash
$ pluralith run --show-changes --show-costs --show-drift

⠿ Initiating Run ⇢ Posting To Pluralith Dashboard
 → Branch detected: test6

→ Verify
  ✔ API key is valid, you are authenticated!
  ✔ Project ID is valid!

→ Plan
  ✔ Execution Plan Generated
  ✔ Secrets Stripped
  ✔ Costs Calculated

→ Export
  ✔ Diagram Generated
  ✘ Posting Run To Pluralith Dashboard Failed
posting run for PR comment failed -> HandleCIRun: request failed -> LogRun: &{400 Bad Request 400 HTTP/2.0 2 0 map[Access-Control-Allow-Origin:[*] Content-Length:[54] Content-Type:[application/json; charset=utf-8] Date:[Fri, 09 Sep 2022 02:39:26 GMT] Etag:[W/"36-Sbx30uwj25sHt5XLThLAnENn3l8"] Server:[Google Frontend] X-Cloud-Trace-Context:[6cf1c75edd4ca9614c36783a7d54f056] X-Powered-By:[Express]] {0xc00024a480} 54 [] false false map[] 0xc0000d7600 0xc00023e0b0}
```

Colud you help me?

**Comment by DanThePutzer** [comment]
Hi @heumsi,

Sorry for the late reply! The issue on the actions repo fell through the cracks!
We actually already fixed this problem, the fix will be shipped with the next release of the CLI!

Once that release is live, it should work locally and in the Github action again as normal.

I'll leave this issue open and comment here again when we release the new CLI, so you know and can try it again.
Is that ok with you?

Best,
Dan

**Comment by heumsi** [comment]
Thanks @DanThePutzer for reply quickly.

Okay. I'll wait for next release. (I want to use as soon as possible 😀)
Thank you for your hard work 👍

**Comment by DanThePutzer** [comment]
Hi @heumsi,

We just released a new version of our CLI yesterday that should (hopefully) fix the issue you had! Would be awesome if you could give it another try and let me know how it went :)

**Comment by heumsi** [comment]
@DanThePutzer Thanx. I will try it again 👍

**Comment by heumsi** [comment]
It works well now. Cool!

I introduced pluralith in [my page](https://heumsi.github.io/hands-on-terraform-with-gcp/03-operation/02-github-based/03-actions-if-pr/03-visualize-modified-resources/) (This is a doc about hands-on-terraform for beginners)
and I'm going to share pluralith with my terraform community.

Thanks @DanThePutzer, and I hope the pluralith project goes smoothly in the future.

**Comment by DanThePutzer** [comment]
@heumsi Wow, thanks a lot for featuring us on your blog!

We've got loads of new stuff in store for you to check out in the near future :)
