### ISSUE TITLE
Panic error on pluralith run

### ISSUE THREAD

**Issue by unuaunco** [Pluralith/pluralith-cli#58]
Hi.

Trying to configure and test pluralith with terraform config and hashicorp/google 4.37.0 provider. Both local and github CI (actions) **run** command returns next error:

```
panic: interface conversion: interface {} is string, not float64

goroutine 1 [running]:
pluralith/cmd.glob..func10(0x180b480?, {0x148352b?, 0x0?, 0x0?})
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/cmd/run.go:62 +0x85b
github.com/spf13/cobra.(*Command).execute(0x180b480, {0x1844e80, 0x0, 0x0})
        /Users/dan/Go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x180b200)
        /Users/dan/Go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/dan/Go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
pluralith/cmd.Execute()
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/cmd/root.go:50 +0x25
main.main()
        /Users/dan/Code/GoProjects/src/github.com/dantheputzer/pluralith-cli/app/main.go:42 +0x1c
```

Terraform plan \ apply works perfect. What can it be?

**Comment by DanThePutzer** [comment]
Hi @unuaunco,

This is a weird one, let me try some things on my end and report back!

**Comment by DanThePutzer** [comment]
@unuaunco I think I found something, but need to do some debugging. Would it be possible for you to send me your orgId and projectId at dan@pluralith.com?

You can find both of those in the Pluralith dashboard.

**Comment by unuaunco** [comment]
@DanThePutzer Thank you for the answer! Requested data was sent.

**Comment by DanThePutzer** [comment]
@unuaunco Apologies for the late reply, but the issue should be fixed!

The issue was that for some reason for your project the orgId was stored as a string rather than a number. Given that we are still in alpha we change a lot of things all the time, this was one of them. Give it another run on your end and let me know how it goes! :)

**Comment by unuaunco** [comment]
@DanThePutzer Thanks, it worked!

**Comment by DanThePutzer** [comment]
Awesome! Thanks for reporting!
