### ISSUE TITLE
Is there a way to integrate only the latest dashboards from a specific branch into the README.md?

### ISSUE THREAD

**Issue by heumsi** [Pluralith/pluralith-cli#59]
Currently, it is not limited to a specific branch, it seems to simply fetch the most up-to-date dashboard.

I want to limit the main branch and include only the latest run in README.md. 
Is there any way to do this? If not, could this be included in future development plans?

**Comment by DanThePutzer** [comment]
Hi @heumsi,

That's a very good point, we'll add that to our roadmap.
Will let you know when its shipped!

**Comment by DanThePutzer** [comment]
Hi @heumsi,

We just shipped a feature for this! We called it **markdown connectors**. On the Pluralith dashboard in the project settings you can now create multiple such **markdown connectors** depending on which branch, which run type (plan, apply, or any) and which filters (changes, costs, drift) you want. You then get a separate URL for each connector to copy into any markdown you'd like.

For example in your use case, to only get **plan runs** on the **main branch** simply create a connector with those settings and copy the URL into your README.

Let me know how it goes! :)

**Comment by heumsi** [comment]
Cool! 
Always thank you very much!
