### ISSUE TITLE
Graph error :  posting run for PR comment failed

### ISSUE THREAD

**Issue by HanHoRang31** [Pluralith/pluralith-cli#73]
Posting Run To Pluralith Dashboard Failed 

➜ sudo pluralith run plan
⠿ Initiating Plan Run ⇢ Posting To Pluralith Dashboard
 → Branch detected: main

→ Verify
  ✔ API key is valid, you are authenticated!
  ✔ Project ID is valid!

→ Plan
  ✔ Execution Plan Generated
  ✔ Plan Cache Created
  ✔ Secrets Stripped
  ✔ Costs Calculated

→ Graph
  ✔ Diagram Generated
  ✘ Posting Run To Pluralith Dashboard Failed
posting run for PR comment failed -> PostGraph: parsing response failed -> LogRun: invalid character 'S' looking for beginning of value

my OS info :
  Model :	MacBook Pro
  Model Identifiers:	MacBookPro15,2
  Process Name :	Qurd core Intel Core i5 
  pluralith-cli verision : pluralith_cli_darwin_amd64_v0.1.18

**Comment by DanThePutzer** [comment]
Hi @HanHoRang31 

Thanks for reporting, I'll look into it and report back here!

**Comment by DanThePutzer** [comment]
@HanHoRang31 I think I might have a gist of what the problem is. Is the infrastructure project you're trying to visualise rather complex?

**Comment by DanThePutzer** [comment]
@HanHoRang31 I think this was an issue with a node process on our backend running out of memory. I've just increased the amount of memory it is allowed to use and hopefully that fixes the issue.

I was unfortunately not able to reproduce on my end, so would be awesome if you could run it again and let me know if it works now!

**Comment by HanHoRang31** [comment]
Thanks for the quick check.
It seems to be a memory problem. Running it again works fine. 
thank you!

**Comment by DanThePutzer** [comment]
Awesome, glad it's running again!

Feel free to let me know how you like the tool in general as well. We're always looking for feedback, would be great to hear what you think about it, what you like and don't like :)

Shoot me an email here if you're open to a quick chat: dan@pluralith.com
