### ISSUE TITLE
Pluralith Desktop UI stuck on Fetching Provider Metadata

### ISSUE THREAD

**Issue by Shocktrooper** [Pluralith/pluralith-cli#74]
After running a Pluralith plan in the CLI locally the UI gets stuck on Generating execution plan with another box saying Fetching Provider Metadata

CLI output:
![image](https://user-images.githubusercontent.com/2646851/201226862-dfcacac8-6362-4292-af10-6c1b9cae0aa6.png)

UI after CLI completes:
![image](https://user-images.githubusercontent.com/2646851/201226913-fca04d21-1340-4f55-8d8e-d8b1660056a2.png)

Other relevant info
CLI-Tool: Powershell
Platform: Windows
Versions:
![image](https://user-images.githubusercontent.com/2646851/201226997-b4b0c8bd-5f96-40fb-a8e0-41c1917c6855.png)

**Comment by DanThePutzer** [comment]
Hi @Shocktrooper 

Thanks for reporting! We're aware of this issue and working on a fix, I'll report back here when we've got one!

**Comment by DanThePutzer** [comment]
Hi @Shocktrooper we just released a new version of the desktop app (`v0.1.20`) that should resolve this issue!
To update simply open the desktop app, it'll download the update automatically and ask you to install it. After that it should work again 👍

**Comment by Shocktrooper** [comment]
Looks good to me!

**Comment by DanThePutzer** [comment]
@Shocktrooper awesome!

If you've got any feedback on the diagram output or if anything looks weird feel free to ping me and don't hesitate to be candid: dan@pluralith.com

Thanks again for reporting! :+1:
