### ISSUE TITLE
posting run for PR comment failed. 400 error

### ISSUE THREAD

**Issue by 2Daeyoung** [Pluralith/pluralith-cli#89]
Hello.
It fails run post whenever I run command 'pluralith run plan'

Error message below.

...
$ pluralith run plan
⠿ Initiating Plan Run ⇢ Posting To Pluralith Dashboard
 → Branch detected: feature/UCMPB-304-EC2템플릿-스케쥴러ASG변경

→ Authentication
  ✔ API key is valid, you are authenticated!

→ Project Setup
  ✔ Existing Org Found
  ✔ Existing Project Found

→ Plan
  ✔ Execution Plan Generated
  ✔ Plan Cache Created
  ✔ Secrets Stripped
  - Cost Calculation Skipped

→ Graph
  ✔ Diagram Generated
  ✘ Posting Run To Pluralith Dashboard Failed
posting run for PR comment failed -> PostGraph: request failed -> LogRun: map[code:400 error:map[] message:Logging run failed]

...

My cli version is 0.1.20

...
Current Version: 0.1.20

✔ You are on the latest version
⠿ Version: 0.1.20
...

Can you check this?

I have tried three terraform files. Two terraform files work well but the other fails.

My terraform line is a little big.

**Comment by DanThePutzer** [comment]
Hi @2Daeyoung thanks for reporting!

This looks like an API issue on our end, I'll investigate and report back here when I found something!

**Comment by 2Daeyoung** [comment]
Thank you so much. I hope this solution's general availability version will be launched as soon as possible.

**Comment by 2Daeyoung** [comment]
I think it happens when branch name includes '/' character.

**Comment by DanThePutzer** [comment]
@2Daeyoung hm that's very interesting! I've investigated a bit on various occasions, but wasn't able to reproduce so far. That hint should help fix the issue, thanks for the heads-up!
