### ISSUE TITLE
Generate Architecture Diagram dry-run without cloud account

### ISSUE THREAD

**Issue by rsrini7** [Pluralith/pluralith-cli#95]
Is there any way to generate arch diagrams without real cloud account ?
Like brainboard.co ?

**Comment by DanThePutzer** [comment]
Hi @rsrini7 thanks for opening an issue!

I'm not sure I understand exactly what the question is. Do you mean manually drawing diagrams like Brainboard, without need to get data from your cloud provider?

**Comment by rsrini7** [comment]
Yes @DanThePutzer. Generate .tf files / import tf to generate Arch diagrams without connecting cloud provider.

**Comment by DanThePutzer** [comment]
@rsrini7 unfortunately that isn't currently possible and would differ quite significantly from our current implementation. Our graphing algorithm needs Terraform state to detect all the dependencies between resources.

**Comment by rsrini7** [comment]
Thanks @DanThePutzer  for your immediate comments. I am closing this issue.
Please suggest, if any other opensource does that or any plan to develop ?
